name: willguimont-website

services:
  dev-linux:
    image: development_website:latest
    build:
      context: .
      # no_cache: true  # Enforce full rebuild
    volumes:
      - .:/root
    tty: true
    stdin_open: true
    network_mode: host

  # dev-osx:
  #   extends:
  #     service: dev-linux
  #   network_mode: bridge
  #   ports:
  #     - 0.0.0.0:4000:4000
#    entrypoint: bash  # For debug purposes (overwride entrypoint)
